### ISSUE TITLE
Collection of Notion Apps and Libraries

### ISSUE THREAD

**Issue by MaaxGr** [Blue-Hope/notion-sdk-py#1]
Hey Dave,

i have started to create a open source project that lists open source projects around the new notion api.
https://github.com/MaaxGr/open-source-notionapi-apps

I have added your Python SDK to it. Is that okay for you?
btw: Is this already stable? Then you are the first inofficial api that is stable in that list :D  

Kind Regards
Max

**Comment by blue-hope** [comment]
it works well, so I deployed XD
but there are some works left to be same as origial js sdk like logging support, type hint support..
It will be really helpful for add my package for it thx!

**Comment by MaaxGr** [comment]
Okay Dave, i have set your project as "Beta" in the list. 
If you think it's stable enough: Drop me a line and i change it. (Or submit a pull request by yourself if you want)
